USE lab;
CREATE TABLE SAILORS(
SID INT PRIMARY KEY,
 SNAME CHAR(25),
 RATING FLOAT,
 AGE INT);
 INSERT INTO SAILORS VALUES ('76843','RAM',3.9,45);
INSERT INTO SAILORS VALUES ('35689','JITH',4.2,32);
INSERT INTO SAILORS VALUES ('76743','BOB',4.5,36);
CREATE TABLE BOATS(
 BID INT PRIMARY KEY,
  BNAME CHAR(20),
 COLOUR CHAR(10)
 );
 INSERT INTO BOATS VALUES ('101','GLORY','RED');
 INSERT INTO BOATS VALUES ('106','BEN','YELLOW');
 INSERT INTO BOATS VALUES ('103','ROLLS','BLUE');
SELECT A.SID, A.SNAME, A.RATING, A.AGE
FROM SAILORS AS A
INNER JOIN RESERVES AS C ON A.SID = C.SID AND C.BID = 101;


SELECT DISTINCT A.SNAME
FROM SAILORS AS A
INNER JOIN RESERVES AS C ON A.SID IN (C.SID);
SELECT A.SID , A.SNAME
FROM RESERVES AS C
INNER JOIN RESERVES AS D ON C.SID <> D.SID AND C.DAY=D.DAY
INNER JOIN SAILORS AS A ON D.SID=A.SID;